### ISSUE TITLE
有没有考虑将纯纯和贝壳开源

### ISSUE THREAD

**Issue by LcxAndroidwawa** [drakeet/about-page#1]

**Comment by drakeet** [comment]
当纯纯打码的用户达到一定规模，当大家都能主动付费和分享它的时候，我可能一高兴就把它们开源了。

**Comment by drakeet** [comment]
我开源过几款应用，于是有人直接拿我的代码基本没修改只改了个名字和作者名字，又上到应用商店当成是他的，令人心寒，而且很多人不懂开源协议也不会去了解，发生各种不遵守开源协议的事情。
