### ISSUE TITLE
功能添加

### ISSUE THREAD

**Issue by Codpoe** [drakeet/about-page#2]
drakeet 大大，你好。

有几个小小的建议：
1. 可不可以增加对 Fragment 的支持？
2. 可否更换 header 的背景色/背景图？

**Comment by drakeet** [comment]
你好
1. 可以，今晚有空实现
2. 原本就可以，由 color primary 控制
Codpoe <notifications@github.com>于2016年10月30日 周日14:18写道：

**Comment by Codpoe** [comment]
@drakeet 

感谢回复。
那 header 的背景色就仅限于跟应用的主色调 color primary 相同了，为什么不独立出来？出于美观的考虑吗？

**Comment by drakeet** [comment]
像 android material design support library 中的很多组件，也都是不支持随意设置颜色的，统一跟随主颜色系列。不过这里考虑到很多新手可能连 color primary 是什么都不知道，或许会支持手动设置背景颜色。
