### ISSUE TITLE
item 之间距离如何设置？

### ISSUE THREAD

**Issue by jngoogle** [drakeet/about-page#6]
您好，item 之间的距离在哪里设置？
比如这个 about-page 中，「介绍」和 下面的「贡献者」之间的距离在哪里可以设置。我在模仿写的时候发现自己的每一个 item 距离很远。

**Comment by drakeet** [comment]
模仿？距离很远？

或许你需要参考我写的各 item layout：
https://github.com/drakeet/about-page/tree/master/library/src/main/res/layout

如果你需要调整 item 之间的距离，你只需要设置某个 item 的 margin bottom 即可。

**Comment by jngoogle** [comment]
好的，多谢。可能是我看你的 about-page 项目不够仔细吧。
另外感谢作者提供这么好的项目！

**Comment by drakeet** [comment]
:D 不客气，这个项目最近计划进行全面修正一下，使其更加好用，同时适配 MultiType 3.3.0 版本，最后还会提供「友情链接」item type，准备启动我之前在微博说的友链计划。

**Comment by jngoogle** [comment]
^W^ 辛苦，辛苦。表示从去年开始看到你的博客开始关注的，好像是记得你跟开复老师合影过吧，233。

**Comment by drakeet** [comment]
哈哈，是的，我自己都快忘了我和开复老师合过影了。
